### ISSUE TITLE
Bot no workie!! 

### ISSUE THREAD

**Issue by GamerSheep** [EpokTarren/astolto#2]
it doesn't work, plez feex

**Comment by EpokTarren** [comment]
What steps are needed to reproduce the issue?

**Comment by GamerSheep** [comment]
> What steps are needed to reproduce the issue?

Just try to use the fecking bot, that's how you reproduce it!

**Comment by GamerSheep** [comment]
> What command doesn't work? When doesn't it work? What goes wrong?

I tried using the a;appraise command, but the only response from the bot is "your appraisal has arrived" without the actual appraisal nor the uwufied message

**Comment by EpokTarren** [comment]
Will look into this.
